import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/Components/SideBar";
import AddThread from "@/Components/AddThread";
import { MenuProvider } from "@/context/MenuContext";
import { ProviderSession } from "@/Components/ProviderSession";
import { getServerSession } from "next-auth";
import { CreatePostProvider } from "@/context/CreatePostContext";
import FeedTabs from "@/Components/FeedTabs";
import CreatePost from "@/Components/CreatePost";
import { AddTopicProvider } from "@/context/AddTopicContext";

const geistSans = Inter({
  variable: "--font-inter-sans",
  weight: ["500", "600", "700", "900"], // 500: medium, 600: semibold, 700: bold, 900: black
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased`}
      >
          <ProviderSession>
            <AddTopicProvider>
              <CreatePostProvider>
                <CreatePost />
                  <MenuProvider>
                    <FeedTabs />
                    <section className="w-full min-h-screen flex">
                      {session && <SideBar />}
                      {children}
                      {session && <AddThread />}
                    </section>
                  </MenuProvider>
              </CreatePostProvider>
            </AddTopicProvider>
          </ProviderSession>
      </body>
    </html>
  );
}
