import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/Components/SideBar";
import AddThread from "@/Components/AddThread";
import { MenuProvider } from "@/context/MenuContext";
import { ProviderSession } from "@/Components/ProviderSession";
import { getServerSession } from "next-auth";
import { CreatePostProvider } from "@/context/CreatePostContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CreatePostProvider>
          <ProviderSession>
            <MenuProvider>
              {/* {pathname} */}
              <section className="w-full min-h-screen flex">
                {session && <SideBar />}
                {children}
                {session && <AddThread />}
              </section>
            </MenuProvider>
          </ProviderSession>
        </CreatePostProvider>
      </body>
    </html>
  );
}
